Fix for HDMI audio playback on EHL platform
projectceladon/device-androidia-sound pull request #29
Opened 2020-06-20 08:36 UTC by gkdeepa

HDMI port on EHL platform is listed as device 7, where as,
the default device for HDMI was set to 3, hence,
adding an additional check for EHL platform.

Tracked-On: OAM-91411
Signed-off-by: gkdeepa <g.k.deepa@intel.com>

2020-06-20 09:48 UTC, gkdeepa commented
@JeevakaPrabu @sgnanase @akodanka @kaushlen

2020-06-20 10:31 UTC, JeevakaPrabu requested changes

2020-06-20 10:31 UTC, JeevakaPrabu commented on hdmi/tinyaudio_hw.c
> +	property_get("ro.hardware.audio",value,"0");
- considering the property is read by vendor shared library, it is better to define a new property like ro.vendor.audio
- There should be space between , and value
- There should be space between , and "
- Indentation not in line with existing code

2020-06-20 12:25 UTC, sgnanase approved these changes

2020-06-20 12:35 UTC, JeevakaPrabu approved these changes

2020-06-21 07:45 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon-autobuild/builds/2320

2020-06-21 07:45 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon-autobuild/builds/2320

2020-06-21 08:54 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon-autobuild/builds/2323

2020-06-21 08:54 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon-autobuild/builds/2323

2020-06-21 08:59 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon-autobuild/builds/2326

2020-06-21 08:59 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp/builders/celadon-autobuild/builds/2326

2020-06-21 14:10 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp/builders/celadon-autobuild/builds/2329

2020-06-21 14:10 UTC, sysopenci reviewed
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp/builders/celadon-autobuild/builds/2329

2020-06-22 07:33 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2086

2020-06-22 07:38 UTC, akodanka approved these changes

2020-06-22 12:02 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2087

Done by "Deepa, G K" <g.k.deepa@intel.com>

2020-06-22 12:03 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1065

Done by "Deepa, G K" <g.k.deepa@intel.com>

2020-06-22 15:02 UTC, merged

2020-06-22 15:03 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Deepa, G K" <g.k.deepa@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/1775