Revert "Revert "Route HDMI audio to right device""
projectceladon/device-androidia-sound pull request #40
Opened 2021-02-08 10:40 UTC by gkdeepa

This reverts commit bb4691bab97c263252d8a414b37139d02128f5eb.

2021-02-09 04:30 UTC, JeevakaPrabu approved these changes

2021-02-09 04:32 UTC, JeevakaPrabu requested changes
please add Tracked-On

2021-02-09 05:16 UTC, akodanka approved these changes

2021-02-09 07:30 UTC, JeevakaPrabu approved these changes

2021-02-10 12:05 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3001

Done by "Deepa, G K" <g.k.deepa@intel.com>

2021-02-10 13:18 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug), CIT-CIV-CML-R(cml_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1509

2021-02-10 14:01 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: cancelled

More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1511

2021-02-10 17:58 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/3005

Done by "Deepa, G K" <g.k.deepa@intel.com>

2021-02-10 19:18 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1512

Done by "Deepa, G K" <g.k.deepa@intel.com>

2021-02-10 23:55 UTC, merged

2021-02-10 23:56 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Deepa, G K" <g.k.deepa@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2235