Fallback to Dummy when no onboard PCH card
projectceladon/device-androidia-sound pull request #65
Opened 2024-04-03 14:57 UTC by gkdeepa

When the PCH card is not card 0 and device 0, fallback to dummy card to avoid sink not ready error at the framework. This ensures that the dummy card is available and helps in

2024-04-03 14:59 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2024-04-03 15:00 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check Android CI Web  for more details.

2024-04-03 15:14 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-03 15:18 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue, Please check Android CI Web  for more details.

2024-04-04 01:36 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-04 05:42 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-05 05:18 UTC, padmashree9110 reviewed
LGTM

2024-04-05 05:22 UTC, balajim001 commented on primary/audio_hw.c
> +        params = pcm_params_get(adev->cardc, PCM_DEVICE, PCM_IN);
Can we handle error situation like this         if (!params)            return -ENOSYS; as before ?

2024-04-05 05:22 UTC, balajim001 requested changes
LGTM

2024-04-08 02:05 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-08 02:54 UTC, padmashree9110 approved these changes

2024-04-08 05:16 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-10 08:00 UTC, balajim001 approved these changes
LGTM

2024-04-11 05:34 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 05:35 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 07:15 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 07:17 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 12:27 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 20:24 UTC, merged

2024-04-11 20:44 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/393